#!/bin/sh

WPATH="/media/fatman/webcam"
OPATH="/media/fatman/webcam/archive"

if [ ! -d "$WPATH" -a ! -x "$WPATH" ]; then
    echo "ERROR: missing path - $WPATH"
    exit
fi

if [ ! -d "$OPATH" -a ! -x "$OPATH" ]; then
    echo "ERROR: missing path - $OPATH"
    exit
fi

DAY=`expr 1`

while [ 1 ]; do
    DSTR=`date -d "$DAY days ago" +"%b_%d_%Y"`
    DAY=`expr $DAY + 1`
    CHECK=`find $WPATH -name $DSTR\*.jpeg`
    if [ -n "$CHECK" ]; then
        echo $DSTR
        mencoder -vf scale=1280:720 -vf-add eq2=2:1:0:1:1:1:1:1 -vf-add pp=tn "mf://$WPATH/$DSTR*.jpeg" -mf fps=24 -o $OPATH/$DSTR.avi -ovc lavc -lavcopts vcodec=mpeg4
        if [ -e $OPATH/$DSTR.avi ]; then
            find $WPATH -name $DSTR\*.jpeg | xargs rm -f
        fi
    else
        exit
    fi
done
